/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package problemas.kotlin

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun `app has greeting`() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
