name: P14
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  P14:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: P14 -
        run: gradle test --tests ListProblem14Test