name: P01 - Encontre o último elemento de uma lista

on:
  push:
    branches: [ main ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: P01 - Encontre o último elemento de uma lista
        run: gradle test --tests Problem01Test