name: Main Gradle Build

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run Gradle Build
        run: ./gradlew build
  lists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run Gradle Build
        run: ./gradlew build
  arithmetic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run Gradle Build
        run: ./gradlew build
  logic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run Gradle Build
        run: ./gradlew build
  binarytrees:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run Gradle Build
        run: ./gradlew build
  multiwaytrees:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run Gradle Build
        run: ./gradlew build
  graphs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run Gradle Build
        run: ./gradlew build
  dancinglinks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run Gradle Build
        run: ./gradlew build
